### ISSUE TITLE
Assembling components

### ISSUE THREAD

**Issue by vivaanusyd** [gueei/DShot-Arduino#7]
Can there be more physical description on what to do? which pins should connect to DShot and which pins are used to change value of throttle? Bearing in mind PORT and PIN might have different meaning in terms of the Arduino. thank you

**Comment by robomaniac** [comment]
```
  esc1.attach(7);               // pin 7 is what connects to ESC
  esc1.setThrottle(target);     // value from 48 to 2047
```

I agree there is not a lot of info how to use. The demo reads the throttle from the serial interface on your computer. Not typical potentiometer from analog port.
